// Auto-generated file. DO NOT EDIT!
package com.danrusu.pods4k.immutableArrays

import com.danrusu.pods4k.utils.Selection
import kotlin.Array
import kotlin.Boolean
import kotlin.Byte
import kotlin.ByteArray
import kotlin.CharSequence
import kotlin.Comparable
import kotlin.Comparator
import kotlin.Double
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.OverloadResolutionByLambdaReturnType
import kotlin.Pair
import kotlin.PublishedApi
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.IndexedValue
import kotlin.collections.Iterable
import kotlin.collections.Iterator
import kotlin.jvm.JvmInline
import kotlin.random.Random
import kotlin.ranges.IntRange
import kotlin.sequences.Sequence

/**
 * Represents an array that cannot have its elements re-assigned.
 *
 * Although this is a class that wraps a regular array, it's really a zero-cost abstraction that gets eliminated
 * at compile time so that variables of this type end up pointing directly at the underlying array.
 *
 * To preserve the same performance as regular arrays, all functions that simply delegate to the same function on
 * the backing array are marked inline.  This won't result in code duplication as it's a direct substitution
 * replacing calls to the wrapper with direct calls to the underlying functions on the backing array.
 */
@Suppress(
    "NOTHING_TO_INLINE",
    "EqualsOrHashCode",
)
@JvmInline
public value class ImmutableByteArray @PublishedApi internal constructor(
    /**
     * The backing array is internal instead of private so that we can have inline functions that delegate to the same
     * function on the backing array.  The backing array won't be accessible from Kotlin code since the auto-generated
     * arrays are in their own module and the internal modifier prevents outside access.  The constructor is also
     * internal preventing anyone from creating an "instance" that points to an array that they have access to.
     *
     * Attempting to bypass the internal visibility from java won't work since this is an inline class so both the
     * field and constructor are mangled by the Kotlin compiler.  While these might appear to be accessible from Java
     * due to the friendly Kotlin interop, these won't actually exist with those names in the generated bytecode
     * resulting in an unknown symbol exception.
     *
     * Therefore, the combination of being internal in its own module along with inline classes makes this effectively
     * private.
     */
    @PublishedApi
    internal val values: ByteArray,
) {
    public inline val size: Int
        get() = values.size

    /**
     * Returns the index of the last element or -1 if the array is empty.
     */
    public inline val lastIndex: Int
        get() = values.lastIndex

    /**
     * Returns the range of valid indices for the array.
     */
    public inline val indices: IntRange
        get() = values.indices

    override fun toString(): String = values.joinToString(prefix = "[", postfix = "]")

    /**
     * See [ByteArray.joinToString]
     */
    public fun joinToString(
        separator: CharSequence = ", ",
        prefix: CharSequence = "",
        postfix: CharSequence = "",
        limit: Int = -1,
        truncated: CharSequence = "...",
        transform: ((element: Byte) -> CharSequence)? = null,
    ): String = values.joinToString(separator, prefix, postfix, limit, truncated, transform)

    public operator fun equals(other: ImmutableByteArray): Boolean {
        if (other.values === this.values) return true
        if (other.size != this.size) return false

        forEachIndexed { index, element ->
            if (other[index] != element) return false
        }
        return true
    }

    /**
     * Immutable Arrays compile to regular arrays in the generated bytecode so this checks if both Immutable Arrays
     * reference the same array instance.
     *
     * Kotlin doesn't allow checking reference equality of inline-class "instances" since auto-boxing the same
     * Immutable Array twice can result in two separate wrapper objects that both represent the same Immutable Array
     * with both wrappers referencing the same backing array instance.  This method allows us to safely check if we're
     * dealing with the same Immutable Array bypassing the auto-boxing concerns.
     */
    public fun referencesSameArrayAs(other: ImmutableByteArray): Boolean {
        return other.values === this.values
    }

    override fun hashCode(): Int {
        // Start with non-zero result so arrays that start with a different number of zero-hash elements end
        // up with different hashCodes
        var hashCode = 7
        for (value in values) {
            hashCode = 31 * hashCode + value.hashCode()
        }
        return hashCode
    }

    /**
     * See [ByteArray.isEmpty]
     */
    public inline fun isEmpty(): Boolean = values.isEmpty()

    /**
     * See [ByteArray.isNotEmpty]
     */
    public inline fun isNotEmpty(): Boolean = values.isNotEmpty()

    /**
     * Returns the element at [index]. This method can be called using the index operator.
     */
    public inline operator fun `get`(index: Int): Byte = values[index]

    /**
     * See [ByteArray.getOrNull]
     */
    public inline fun getOrNull(index: Int): Byte? = values.getOrNull(index)

    public operator fun component1(): Byte = get(0)

    public operator fun component2(): Byte = get(1)

    public operator fun component3(): Byte = get(2)

    public operator fun component4(): Byte = get(3)

    public operator fun component5(): Byte = get(4)

    /**
     * See [ByteArray.single]
     */
    public inline fun single(): Byte = values.single()

    /**
     * See [ByteArray.single]
     */
    public inline fun single(predicate: (element: Byte) -> Boolean): Byte {
        return values.single(predicate)
    }

    /**
     * See [ByteArray.singleOrNull]
     */
    public inline fun singleOrNull(): Byte? = values.singleOrNull()

    /**
     * See [ByteArray.singleOrNull]
     */
    public inline fun singleOrNull(predicate: (element: Byte) -> Boolean): Byte? {
        return values.singleOrNull(predicate)
    }

    /**
     * See [ByteArray.first]
     */
    public inline fun first(): Byte = values.first()

    /**
     * See [ByteArray.first]
     */
    public inline fun first(predicate: (element: Byte) -> Boolean): Byte {
        return values.first(predicate)
    }

    /**
     * See [ByteArray.firstOrNull]
     */
    public inline fun firstOrNull(): Byte? = values.firstOrNull()

    /**
     * See [ByteArray.firstOrNull]
     */
    public inline fun firstOrNull(predicate: (element: Byte) -> Boolean): Byte? {
        return values.firstOrNull(predicate)
    }

    /**
     * See [ByteArray.last]
     */
    public inline fun last(): Byte = values.last()

    /**
     * See [ByteArray.last]
     */
    public inline fun last(predicate: (element: Byte) -> Boolean): Byte {
        return values.last(predicate)
    }

    /**
     * See [ByteArray.lastOrNull]
     */
    public inline fun lastOrNull(): Byte? = values.lastOrNull()

    /**
     * See [ByteArray.lastOrNull]
     */
    public inline fun lastOrNull(predicate: (element: Byte) -> Boolean): Byte? {
        return values.lastOrNull(predicate)
    }

    /**
     * See [ByteArray.random]
     */
    public inline fun random(): Byte = values.random()

    /**
     * See [ByteArray.random]
     */
    public inline fun random(random: Random): Byte = values.random(random)

    /**
     * See [ByteArray.randomOrNull]
     */
    public inline fun randomOrNull(): Byte? = values.randomOrNull()

    /**
     * See [ByteArray.randomOrNull]
     */
    public inline fun randomOrNull(random: Random): Byte? = values.randomOrNull(random)

    /**
     * See [ByteArray.iterator]
     */
    public inline operator fun iterator(): Iterator<Byte> = values.iterator()

    /**
     * See [ByteArray.asIterable]
     */
    public inline fun asIterable(): Iterable<Byte> = values.asIterable()

    /**
     * See [ByteArray.withIndex]
     */
    public inline fun withIndex(): Iterable<IndexedValue<Byte>> = values.withIndex()

    /**
     * See [ByteArray.asSequence]
     */
    public inline fun asSequence(): Sequence<Byte> = values.asSequence()

    /**
     * Splits this Immutable Array into chunks that each contain [size] elements.  The resulting Immutable
     * Array contains a nested Immutable Array for each chunk.  The last chunk may contain fewer elements when the
     * size isn't a perfect multiple of the [size].
     */
    public fun chunked(size: Int): ImmutableArray<ImmutableByteArray> {
        return windowed(size = size, step = size, partialWindows = true)
    }

    /**
     * Returns an Immutable Array of Immutable Arrays where each nested Immutable Array represents a sliding window
     * with [size] elements.  The sliding window jumps over [step] elements at a time to copy subsequent windows.
     *
     * @param size the number of elements to copy in each window
     * @param step the start of each window jumps forward by this amount
     * @param partialWindows controls whether to include windows with fewer than [size] elements when the sliding
     * window overlaps past the end.
     */
    public fun windowed(
        size: Int,
        step: Int = 1,
        partialWindows: Boolean = false,
    ): ImmutableArray<ImmutableByteArray> {
        require(size > 0) { "The size must be positive" }
        require(step > 0) { "The step must be positive" }

        val numWindows = when {
            partialWindows -> (this.size + step - 1) / step
            this.size >= size -> (this.size - size) / step + 1
            else -> 0
        }
        var windowStart = -step // start negative as it gets incremented by step right away
        return ImmutableArray(numWindows) {
            windowStart += step
            copyFrom(values, windowStart, size.coerceAtMost(this.size - windowStart))
        }
    }

    /**
     * See [ByteArray.forEach]
     */
    public inline fun forEach(action: (element: Byte) -> Unit) {
        values.forEach(action)
    }

    /**
     * See [ByteArray.forEachIndexed]
     */
    public inline fun forEachIndexed(action: (index: Int, element: Byte) -> Unit) {
        values.forEachIndexed(action)
    }

    /**
     * See [ByteArray.all]
     */
    public inline fun all(predicate: (predicate: Byte) -> Boolean): Boolean {
        return values.all(predicate)
    }

    /**
     * See [ByteArray.any]
     */
    public inline fun any(predicate: (predicate: Byte) -> Boolean): Boolean {
        return values.any(predicate)
    }

    /**
     * See [ByteArray.none]
     */
    public inline fun none(predicate: (predicate: Byte) -> Boolean): Boolean {
        return values.none(predicate)
    }

    /**
     * See [ByteArray.count]
     */
    public inline fun count(predicate: (predicate: Byte) -> Boolean): Int {
        return values.count(predicate)
    }

    /**
     * See [ByteArray.indexOfFirst]
     */
    public inline fun indexOfFirst(predicate: (element: Byte) -> Boolean): Int {
        return values.indexOfFirst(predicate)
    }

    /**
     * See [ByteArray.indexOfLast]
     */
    public inline fun indexOfLast(predicate: (element: Byte) -> Boolean): Int {
        return values.indexOfLast(predicate)
    }

    /**
     * See [ByteArray.sumOf]
     */
    @OverloadResolutionByLambdaReturnType
    public inline fun sumOf(selector: (element: Byte) -> Int): Int = values.sumOf(selector)

    /**
     * See [ByteArray.sumOf]
     */
    @OverloadResolutionByLambdaReturnType
    public inline fun sumOf(selector: (element: Byte) -> Long): Long = values.sumOf(selector)

    /**
     * See [ByteArray.sumOf]
     */
    @OverloadResolutionByLambdaReturnType
    public inline fun sumOf(selector: (element: Byte) -> Double): Double = values.sumOf(selector)

    /**
     * Returns the sum of all values produced by the [selector] function applied to each element.
     */
    @OverloadResolutionByLambdaReturnType
    public inline fun sumOf(selector: (element: Byte) -> Float): Float {
        var sum = 0.0f
        for (element in values) {
            sum += selector(element)
        }
        return sum
    }

    /**
     * Returns an Immutable Array containing the first [n] elements.
     *
     * @throws IllegalArgumentException if [n] is negative.
     */
    public fun take(n: Int): ImmutableByteArray {
        require(n >= 0) { "Requested element count $n is less than zero." }
        if (n >= size) return this

        return copyFrom(source = values, startIndex = 0, size = n)
    }

    /**
     * Returns an Immutable Array containing the first elements that satisfy the [predicate].
     */
    public inline fun takeWhile(predicate: (element: Byte) -> Boolean): ImmutableByteArray {
        for (index in 0..lastIndex) {
            if (!predicate(values[index])) {
                return take(index)
            }
        }
        return this
    }

    /**
     * Returns an Immutable Array containing the last [n] elements.
     *
     * @throws IllegalArgumentException if [n] is negative.
     */
    public fun takeLast(n: Int): ImmutableByteArray {
        require(n >= 0) { "Requested element count $n is less than zero." }
        if (n >= size) return this

        return copyFrom(source = values, startIndex = size - n, size = n)
    }

    /**
     * Returns an Immutable Array containing the last elements that satisfy the [predicate].
     */
    public inline fun takeLastWhile(predicate: (element: Byte) -> Boolean): ImmutableByteArray {
        for (index in lastIndex downTo 0) {
            if (!predicate(values[index])) {
                return takeLast(size - index - 1)
            }
        }
        return this
    }

    /**
     * Returns an Immutable Array containing all the elements except the first n elements.
     *
     * @throws IllegalArgumentException if [n] is negative.
     */
    public fun drop(n: Int): ImmutableByteArray {
        require(n >= 0) { "Requested element count $n is less than zero." }

        return takeLast((size - n).coerceAtLeast(0))
    }

    /**
     * Returns an Immutable Array containing all the elements except the first elements that satisfy the [predicate].
     */
    public inline fun dropWhile(predicate: (element: Byte) -> Boolean): ImmutableByteArray {
        for (index in 0..lastIndex) {
            if (!predicate(values[index])) {
                return takeLast(size - index)
            }
        }
        return EMPTY
    }

    /**
     * Returns an Immutable Array containing all the elements except the last n elements.
     *
     * @throws IllegalArgumentException if [n] is negative.
     */
    public fun dropLast(n: Int): ImmutableByteArray {
        require(n >= 0) { "Requested element count $n is less than zero." }

        return take((size - n).coerceAtLeast(0))
    }

    /**
     * Returns an Immutable Array containing all the elements except the last elements that satisfy the [predicate].
     */
    public inline fun dropLastWhile(predicate: (element: Byte) -> Boolean): ImmutableByteArray {
        for (index in lastIndex downTo 0) {
            if (!predicate(values[index])) {
                return take(index + 1)
            }
        }
        return EMPTY
    }

    /**
     * Returns an Immutable Array containing only the elements matching the given [predicate].
     */
    public inline fun filter(crossinline predicate: (element: Byte) -> Boolean): ImmutableByteArray {
        if (isEmpty()) return this

        val selection = Selection(numElements = size) { index -> predicate(this[index]) }
        return select(selection)
    }

    /**
     * Returns an Immutable Array containing only the elements matching the given [predicate].
     */
    public inline fun filterIndexed(crossinline predicate: (index: Int, element: Byte) -> Boolean): ImmutableByteArray {
        if (isEmpty()) return this

        val selection = Selection(numElements = size) { index -> predicate(index, this[index]) }
        return select(selection)
    }

    /**
     * Returns an Immutable Array containing only the elements that don't match the [predicate].
     */
    public inline fun filterNot(crossinline predicate: (element: Byte) -> Boolean): ImmutableByteArray {
        if (isEmpty()) return this

        val selection = Selection(numElements = size) { index -> !predicate(this[index]) }
        return select(selection)
    }

    /**
     * Returns an Immutable Array containing only the elements from indices indicated by the [selection].
     */
    @PublishedApi
    internal fun select(selection: Selection): ImmutableByteArray {
        val resultSize = selection.numSelectedElements
        when (resultSize) {
            0 -> return EMPTY
            size -> return this
        }
        val result = ByteArray(resultSize)
        var resultIndex = 0
        selection.forEachSelectedIndex { originalIndex ->
            result[resultIndex++] = this[originalIndex]
        }
        return ImmutableByteArray(result)
    }

    /**
     * Creates a pair of Immutable Arrays, where the first contains elements for which the predicate yielded true, and
     * the second contains the other elements.
     */
    public fun partition(predicate: (element: Byte) -> Boolean): Pair<ImmutableByteArray, ImmutableByteArray> {
        val selection = Selection(numElements = size) { index -> predicate(this[index]) }
        val numSelectedElements = selection.numSelectedElements

        if (numSelectedElements == 0) return Pair(EMPTY, this)
        if (numSelectedElements == size) return Pair(this, EMPTY)

        val first = ByteArray(numSelectedElements)
        var firstIndex = 0
        selection.forEachSelectedIndex { originalIndex ->
            first[firstIndex++] = values[originalIndex]
        }

        val second = ByteArray(size - numSelectedElements)
        var secondIndex = 0
        selection.forEachUnselectedIndex { originalIndex ->
            second[secondIndex++] = values[originalIndex]
        }
        return Pair(ImmutableByteArray(first), ImmutableByteArray(second))
    }

    /**
     * @return the first element which the [selector] yields the smallest value.
     * @throws NoSuchElementException if this ImmutableByteArray is empty
     */
    public inline fun <R : Comparable<R>> minBy(selector: (element: Byte) -> R): Byte {
        var minElement = first()
        if (size == 1) return minElement

        var minValue = selector(minElement)
        for (i in 1..lastIndex) {
            val currentElement = values[i]
            val currentValue = selector(currentElement)
            if (currentValue < minValue) {
                minElement = currentElement
                minValue = currentValue
            }
        }
        return minElement
    }

    /**
     * @return the first element which the [selector] yields the smallest value, or null if empty
     */
    public inline fun <R : Comparable<R>> minByOrNull(selector: (element: Byte) -> R): Byte? {
        return if (isEmpty()) null else minBy(selector)
    }

    /**
     * @return the first element which the [selector] yields the largest value.
     * @throws NoSuchElementException if this ImmutableByteArray is empty
     */
    public inline fun <R : Comparable<R>> maxBy(selector: (element: Byte) -> R): Byte {
        var maxElement = first()
        if (size == 1) return maxElement

        var maxValue = selector(maxElement)
        for (i in 1..lastIndex) {
            val currentElement = values[i]
            val currentValue = selector(currentElement)
            if (currentValue > maxValue) {
                maxElement = currentElement
                maxValue = currentValue
            }
        }
        return maxElement
    }

    /**
     * @return the first element which the [selector] yields the largest value, or null if empty
     */
    public inline fun <R : Comparable<R>> maxByOrNull(selector: (element: Byte) -> R): Byte? {
        return if (isEmpty()) null else maxBy(selector)
    }

    /**
     * @return the first element having the smallest value according to the provided [comparator].
     * @throws NoSuchElementException if this ImmutableByteArray is empty
     */
    public fun minWith(comparator: Comparator<in Byte>): Byte {
        var minElement = first()
        if (size == 1) return minElement

        for (i in 1..lastIndex) {
            val currentElement = values[i]
            if (comparator.compare(minElement, currentElement) > 0) {
                minElement = currentElement
            }
        }
        return minElement
    }

    /**
     * Returns the first element having the smallest value according to the provided [comparator] or null if empty.
     */
    public fun minWithOrNull(comparator: Comparator<in Byte>): Byte? {
        return if (isEmpty()) null else minWith(comparator)
    }

    /**
     * @return the first element having the largest value according to the provided [comparator].
     * @throws NoSuchElementException if this ImmutableByteArray is empty
     */
    public fun maxWith(comparator: Comparator<in Byte>): Byte {
        var maxElement = first()
        if (size == 1) return maxElement

        for (i in 1..lastIndex) {
            val currentElement = values[i]
            if (comparator.compare(maxElement, currentElement) < 0) {
                maxElement = currentElement
            }
        }
        return maxElement
    }

    /**
     * Returns the first element having the largest value according to the provided [comparator] or null if empty.
     */
    public fun maxWithOrNull(comparator: Comparator<in Byte>): Byte? {
        return if (isEmpty()) null else maxWith(comparator)
    }

    /**
     * Leaves this Immutable Array as is and returns an ImmutableByteArray with all elements sorted
     * according to the natural sort order of the value returned by the [selector].
     *
     * The sort is _stable_ so equal elements preserve their order relative to each other after sorting.
     */
    public inline fun <R : Comparable<R>> sortedBy(crossinline selector: (element: Byte) -> R?): ImmutableByteArray {
        return sortedWith(compareBy(selector))
    }

    /**
     * Leaves this Immutable Array as is and returns an ImmutableByteArray with all elements sorted
     * according to the reverse natural sort order of the value returned by the [selector].
     *
     * The sort is _stable_ so equal elements preserve their order relative to each other after sorting.
     */
    public inline fun <R : Comparable<R>> sortedByDescending(
        crossinline selector: (element: Byte) -> R?,
    ): ImmutableByteArray {
        return sortedWith(compareByDescending(selector))
    }

    /**
     * Leaves this Immutable Array as is and returns an [ImmutableByteArray] with all elements sorted
     * according to the specified [comparator].
     */
    public fun sortedWith(comparator: Comparator<in Byte>): ImmutableByteArray {
        if (size <= 1) return this

        val temp = values.toTypedArray()
        temp.sortWith(comparator)
        return temp.toImmutableArray()
    }

    /**
     * Leaves this Immutable Array as is and returns an [ImmutableByteArray] with all elements shuffled.
     */
    public fun shuffled(): ImmutableByteArray {
        if (size <= 1) return this

        val backingArray = values.copyOf().apply { shuffle() }
        return ImmutableByteArray(backingArray)
    }

    /**
     * Leaves this Immutable Array as is and returns an [ImmutableByteArray] with all elements shuffled.
     */
    public fun shuffled(random: Random): ImmutableByteArray {
        if (size <= 1) return this

        val backingArray = values.copyOf().apply { shuffle(random) }
        return ImmutableByteArray(backingArray)
    }

    /**
     * Returns an Immutable Array containing only the distinct elements from this Immutable Array.
     *
     * Iteration order is preserved and subsequent duplicate elements are ignored.
     */
    public fun distinct(): ImmutableByteArray {
        if (size <= 1) return this

        val distinctValues = HashSet<Byte>()
        return filter { distinctValues.add(it) }
    }

    /**
     * Returns an Immutable Array containing only the elements having distinct keys returned by the [selector]
     */
    public inline fun <K> distinctBy(crossinline selector: (element: Byte) -> K): ImmutableByteArray {
        if (size <= 1) return this

        val keys = HashSet<K>()
        return filter { keys.add(selector(it)) }
    }

    public companion object {
        @PublishedApi
        internal val EMPTY: ImmutableByteArray = ImmutableByteArray(ByteArray(0))

        /**
         * Returns an ImmutableByteArray instance of the specified [size], where each element is calculated by
         * calling the [init] function.
         *
         * [init] is called sequentially, starting at index 0, to initialize the array with each element at its given
         * index.
         *
         * Implementation:
         * We're using the invoke operator instead of a regular constructor so that we can declare it inline.  The call
         * site will look like a regular constructor call.
         */
        public inline operator fun invoke(size: Int, `init`: (index: Int) -> Byte): ImmutableByteArray {
            if (size == 0) return EMPTY

            val backingArray = ByteArray(size) { index -> init(index) }
            return ImmutableByteArray(backingArray)
        }

        /**
         * Returns an ImmutableByteArray with the first [size] elements copied from [source] starting from [startIndex].
         */
        public fun copyFrom(
            source: ByteArray,
            startIndex: Int,
            size: Int,
        ): ImmutableByteArray {
            if (size == 0) return EMPTY

            val backingArray = ByteArray(size)
            System.arraycopy(source, startIndex, backingArray, 0, size)
            return ImmutableByteArray(backingArray)
        }
    }

    /**
     * Builder to create Immutable Arrays when the resulting size isn't known in advance.
     *
     * Note: While the generated Immutable Array is thread-safe, this builder is not.  External concurrency
     * control is required when sharing builders between threads.
     *
     * @param initialCapacity The initial capacity of the temporary array where the values are
     * accumulated.  A larger value reduces the number of times it's resized as elements get added.
     */
    public class Builder(initialCapacity: Int = 10) {
        public var size: Int = 0
            private set

        private var values: ByteArray = ByteArray(initialCapacity)

        public fun add(element: Byte): Builder {
            ensureCapacity(size + 1)
            values[size++] = element
            return this
        }

        /**
         * Adds the [element] to the builder.
         */
        public operator fun plusAssign(element: Byte) {
            add(element)
        }

        public fun addAll(elements: ByteArray): Builder {
            ensureCapacity(size + elements.size)
            System.arraycopy(elements, 0, values, size, elements.size)
            size += elements.size
            return this
        }

        public fun addAll(elements: Array<Byte>): Builder {
            ensureCapacity(size + elements.size)
            for (element in elements) {
                values[size++] = element
            }
            return this
        }

        public fun addAll(elements: ImmutableByteArray): Builder {
            ensureCapacity(size + elements.size)
            System.arraycopy(elements.values, 0, values, size, elements.size)
            size += elements.size
            return this
        }

        public fun addAll(elements: ImmutableArray<Byte>): Builder {
            ensureCapacity(size + elements.size)
            for (element in elements) {
                values[size++] = element
            }
            return this
        }

        public fun addAll(elements: Iterable<Byte>): Builder {
            if (elements is Collection) {
                ensureCapacity(size + elements.size)
                for (element in elements) {
                    values[size++] = element
                }
                return this
            }
            for (element in elements) {
                add(element)
            }
            return this
        }

        public fun addAll(elements: Sequence<Byte>): Builder {
            elements.forEach { add(it) }
            return this
        }

        /**
         * Returns an Immutable Array containing the elements that were added.
         */
        public fun build(): ImmutableByteArray {
            if (size == 0) return EMPTY
            if (size == values.size) return ImmutableByteArray(values)

            return copyFrom(source = values, startIndex = 0, size = size)
        }

        private fun ensureCapacity(minCapacity: Int) {
            val newCapacity = BuilderUtils.computeNewCapacity(values.size, minCapacity)
            if (newCapacity == values.size) return

            values = values.copyOf(newCapacity)
        }
    }
}
